---
name: Run Renovate

on:
  workflow_call:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: "false"
        required: false
        type: string
      renovateLogLevel:
        description: "Log-Level"
        default: "debug"
        required: false
        type: string
      configurationFile:
        description: "Renovate configuration file"
        default: ".github/renovate.json5"
        required: false
        type: string
    secrets:
      app_id:
        description: "App ID of the application used to generate a token"
        required: true
      app_private_key:
        description: "Private key of the application used to generate a token"
        required: true
      dockerhub_username:
        description: "Dockerhub username for authenticated pulls."
        required: true
      dockerhub_token:
        description: "Dockerhub personal access token."
        required: true

jobs:
  renovate:
    name: Renovate
    runs-on: self-hosted
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}
              
      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.app_id }}
          private_key: ${{ secrets.app_private_key }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: "${{ steps.generate-token.outputs.token }}"

      - name: Renovate
        uses: renovatebot/github-action@v34.94.0
        env:
          DRY_RUN: ${{ inputs.dryRun }}
          LOG_LEVEL: ${{ inputs.renovateLogLevel }}
        with:
          configurationFile: ${{ inputs.configurationFile }}
          token: "${{ steps.generate-token.outputs.token }}"
